CREATE TABLE ZACCESSRESOURCEPERMISSION ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSHORTCUT INTEGER, ZIDENTIFIER VARCHAR, ZDATA BLOB );

CREATE TABLE ZAUTOSHORTCUTSPREFERENCES ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZLASTSYNCEDHASH INTEGER, ZSIRIENABLED INTEGER, ZSPOTLIGHTENABLED INTEGER, ZAPPNAME VARCHAR, ZIDENTIFIER VARCHAR, ZAPPDESCRIPTOR BLOB, ZCLOUDKITMETADATA BLOB, ZDISABLEDAUTOSHORTCUTS BLOB );

CREATE TABLE ZCLOUDKITSYNCTOKEN ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZCOHERENCESYNCENABLED INTEGER, ZDATE TIMESTAMP, ZACCOUNT VARCHAR, ZIDENTIFIER VARCHAR, ZLASTORDERINGCLOUDKITRECORDMETADATA BLOB, ZLASTORDERINGDATA BLOB, ZSERVERCHANGETOKENDATA BLOB, ZSYNCENGINEMETADATA BLOB, ZSYNCFLAGSCLOUDKITRECORDMETADATA BLOB );

CREATE TABLE ZCOLLECTION ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZLASTSYNCEDENCRYPTEDSCHEMAVERSION INTEGER, ZTEMPORARYSYNCFOLDERICON INTEGER, ZTOMBSTONED INTEGER, ZWANTEDENCRYPTEDSCHEMAVERSION INTEGER, ZIDENTIFIER VARCHAR, ZTEMPORARYSYNCFOLDERNAME VARCHAR, ZCLOUDKITFOLDERRECORDMETADATA BLOB, ZCLOUDKITORDERINGRECORDMETADATA BLOB, ZLASTREMOTECOLLECTIONORDERINGDATA BLOB, ZLASTREMOTECOLLECTIONORDERINGSUBSETDATA BLOB, ZLASTREMOTESHORTCUTORDERINGDATA BLOB );

CREATE TABLE ZFILESTATE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZLASTMODIFIEDDATE TIMESTAMP, ZIDENTIFIER VARCHAR, ZPATH VARCHAR );

CREATE TABLE ZLIBRARY ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZLASTSYNCEDHASH INTEGER, ZRESETVERSION INTEGER, ZSYNCHASH INTEGER, ZIDENTIFIER VARCHAR, ZCLOUDKITRECORDMETADATA BLOB, ZDATA BLOB );

CREATE TABLE ZPERSISTEDSERIALIZEDPARAMETERS ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZBADGETYPE INTEGER, ZIDENTIFIER VARCHAR, ZQUERYNAME VARCHAR, ZDATA BLOB );

CREATE TABLE ZSHORTCUT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZACTIONCOUNT INTEGER, ZDISABLEDONLOCKSCREEN INTEGER, ZHASOUTPUTACTION INTEGER, ZHASOUTPUTFALLBACK INTEGER, ZHASSHORTCUTINPUTVARIABLES INTEGER, ZHIDDENFROMLIBRARYANDSYNC INTEGER, ZHIDDENFROMWIDGET INTEGER, ZLASTSYNCEDENCRYPTEDSCHEMAVERSION INTEGER, ZLASTSYNCEDHASH INTEGER, ZRECEIVESINPUTFROMSEARCH INTEGER, ZRECEIVESONSCREENCONTENT INTEGER, ZREMOTEQUARANTINESTATUSVALUE INTEGER, ZRUNEVENTSCOUNT INTEGER, ZSHOULDAUTOUPDATEASSOCIATEDAPPBUNDLEIDENTIFIER INTEGER, ZSHOWINSEARCH INTEGER, ZSPOTLIGHTSYNCHASH INTEGER, ZSYNCHASH INTEGER, ZTOMBSTONED INTEGER, ZTRIGGERCOUNT INTEGER, ZWANTEDENCRYPTEDSCHEMAVERSION INTEGER, ZACTIONS INTEGER, ZCONFLICTOF INTEGER, ZICON INTEGER, ZQUARANTINE INTEGER, ZCREATIONDATE TIMESTAMP, ZLASTRUNEVENTDATE TIMESTAMP, ZMODIFICATIONDATE TIMESTAMP, ZACTIONSDESCRIPTION VARCHAR, ZASSOCIATEDAPPBUNDLEIDENTIFIER VARCHAR, ZGALLERYIDENTIFIER VARCHAR, ZLASTMIGRATEDCLIENTVERSION VARCHAR, ZLASTSAVEDONDEVICENAME VARCHAR, ZMINIMUMCLIENTVERSION VARCHAR, ZNAME VARCHAR, ZPHRASE VARCHAR, ZSEARCHATTRIBUTIONAPPBUNDLEIDENTIFIER VARCHAR, ZSOURCE VARCHAR, ZWORKFLOWID VARCHAR, ZWORKFLOWSUBTITLE VARCHAR, ZCLOUDKITRECORDMETADATA BLOB, ZIMPORTQUESTIONSDATA BLOB, ZINPUTCLASSESDATA BLOB, ZNOINPUTBEHAVIORDATA BLOB, ZOUTPUTCLASSESDATA BLOB, ZREMOTEQUARANTINEHASH BLOB );

CREATE TABLE ZSHORTCUTACTIONS ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSHORTCUT INTEGER, ZDATA BLOB );

CREATE TABLE ZSHORTCUTBOOKMARK ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZIDENTIFIER VARCHAR, ZPATH VARCHAR, ZBOOKMARKDATA BLOB );

CREATE TABLE ZSHORTCUTICON ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZBACKGROUNDCOLORVALUE INTEGER, ZGLYPHNUMBER INTEGER, ZWORKFLOW INTEGER );

CREATE TABLE ZSHORTCUTQUARANTINE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZWORKFLOW INTEGER, ZIMPORTDATE TIMESTAMP, ZSOURCEAPPIDENTIFIER VARCHAR );

CREATE TABLE ZSHORTCUTRUNEVENT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZOUTCOME INTEGER, ZSHORTCUT INTEGER, ZTRIGGER INTEGER, ZDATE TIMESTAMP, ZIDENTIFIER VARCHAR, ZSOURCE VARCHAR );

CREATE TABLE ZSMARTPROMPTPERMISSION ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSHORTCUT INTEGER, ZACTIONUUID VARCHAR, ZIDENTIFIER VARCHAR, ZDATA BLOB );

CREATE TABLE ZTRACKEDFILESYSTEMNODE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZIGNORINGSUBFOLDERS INTEGER, ZISDIRECTORY INTEGER, ZIDENTIFIER VARCHAR, ZBOOKMARK BLOB, ZFILESLIST BLOB, ZTRIGGERS BLOB );

CREATE TABLE ZTRIGGER ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZEDITABLESHORTCUT INTEGER, ZENABLED INTEGER, ZNOTIFICATIONLEVEL INTEGER, ZPOTENTIALLOOPDETECTED INTEGER, ZSHOULDNOTIFY INTEGER, ZSHOULDPROMPT INTEGER, ZSHOULDRECUR INTEGER, ZSOURCE INTEGER, ZSHORTCUT INTEGER, ZDISABLEMENTREASON VARCHAR, ZIDENTIFIER VARCHAR, ZDATA BLOB, ZSELECTEDENTRYMETADATA BLOB );

CREATE TABLE ZTRIGGEREVENT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZCONFIRMED INTEGER, ZPAUSED INTEGER, ZTRIGGER INTEGER, ZDATECREATED TIMESTAMP, ZIDENTIFIER VARCHAR, ZEVENTINFO BLOB );

CREATE TABLE ZTRUSTEDDOMAIN ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSHORTCUT INTEGER, ZDOMAIN VARCHAR );

CREATE TABLE ZVCVOICESHORTCUTMANAGEDOBJECT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZISMARKEDASDELETED INTEGER, ZDATECREATED TIMESTAMP, ZDATELASTMODIFIED TIMESTAMP, ZASSOCIATEDAPPBUNDLEIDENTIFIER VARCHAR, ZPHRASE VARCHAR, ZSHORTCUTDESCRIPTION VARCHAR, ZSHORTCUTNAME VARCHAR, ZIDENTIFIER BLOB, ZKEYIMAGEDATA BLOB, ZSERIALIZEDWORKFLOWDATA BLOB );

CREATE TABLE ZVCVOICESHORTCUTSUGGESTIONLISTMANAGEDOBJECT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSHORTCUTAVAILABILITYOPTIONS INTEGER, ZASSOCIATEDAPPBUNDLEIDENTIFIER VARCHAR, ZSERIALIZEDSUGGESTIONS BLOB );

CREATE TABLE ZVCVOICESHORTCUTSYNCSTATEMANAGEDOBJECT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZHASSYNCED INTEGER, ZVOICESHORTCUT INTEGER, ZSYNCSERVICEIDENTIFIER VARCHAR, ZMETADATA BLOB );

CREATE INDEX ZACCESSRESOURCEPERMISSION_ZSHORTCUT_INDEX ON ZACCESSRESOURCEPERMISSION (ZSHORTCUT);

CREATE UNIQUE INDEX Z_AccessResourcePermission_UNIQUE_identifier_shortcut ON ZACCESSRESOURCEPERMISSION (ZIDENTIFIER COLLATE BINARY ASC, ZSHORTCUT COLLATE BINARY ASC);

CREATE UNIQUE INDEX Z_CloudKitSyncToken_UNIQUE_identifier ON ZCLOUDKITSYNCTOKEN (ZIDENTIFIER COLLATE BINARY ASC);

CREATE UNIQUE INDEX Z_Collection_UNIQUE_identifier ON ZCOLLECTION (ZIDENTIFIER COLLATE BINARY ASC);

CREATE UNIQUE INDEX Z_PersistedSerializedParameters_UNIQUE_data_identifier_queryName ON ZPERSISTEDSERIALIZEDPARAMETERS (ZDATA COLLATE BINARY ASC, ZIDENTIFIER COLLATE BINARY ASC, ZQUERYNAME COLLATE BINARY ASC);

CREATE INDEX ZSHORTCUT_ZACTIONS_INDEX ON ZSHORTCUT (ZACTIONS);

CREATE INDEX ZSHORTCUT_ZCONFLICTOF_INDEX ON ZSHORTCUT (ZCONFLICTOF);

CREATE INDEX ZSHORTCUT_ZICON_INDEX ON ZSHORTCUT (ZICON);

CREATE INDEX ZSHORTCUT_ZQUARANTINE_INDEX ON ZSHORTCUT (ZQUARANTINE);

CREATE UNIQUE INDEX Z_Shortcut_UNIQUE_workflowID ON ZSHORTCUT (ZWORKFLOWID COLLATE BINARY ASC);

CREATE INDEX ZSHORTCUTACTIONS_ZSHORTCUT_INDEX ON ZSHORTCUTACTIONS (ZSHORTCUT);

CREATE UNIQUE INDEX Z_ShortcutBookmark_UNIQUE_path_identifier ON ZSHORTCUTBOOKMARK (ZPATH COLLATE BINARY ASC, ZIDENTIFIER COLLATE BINARY ASC);

CREATE INDEX ZSHORTCUTICON_ZWORKFLOW_INDEX ON ZSHORTCUTICON (ZWORKFLOW);

CREATE INDEX ZSHORTCUTQUARANTINE_ZWORKFLOW_INDEX ON ZSHORTCUTQUARANTINE (ZWORKFLOW);

CREATE INDEX ZSHORTCUTRUNEVENT_ZSHORTCUT_INDEX ON ZSHORTCUTRUNEVENT (ZSHORTCUT);

CREATE INDEX ZSHORTCUTRUNEVENT_ZTRIGGER_INDEX ON ZSHORTCUTRUNEVENT (ZTRIGGER);

CREATE UNIQUE INDEX Z_ShortcutRunEvent_UNIQUE_identifier ON ZSHORTCUTRUNEVENT (ZIDENTIFIER COLLATE BINARY ASC);

CREATE INDEX ZSMARTPROMPTPERMISSION_ZSHORTCUT_INDEX ON ZSMARTPROMPTPERMISSION (ZSHORTCUT);

CREATE UNIQUE INDEX Z_TrackedFilesystemNode_UNIQUE_identifier ON ZTRACKEDFILESYSTEMNODE (ZIDENTIFIER COLLATE BINARY ASC);

CREATE INDEX ZTRIGGER_ZSHORTCUT_INDEX ON ZTRIGGER (ZSHORTCUT);

CREATE UNIQUE INDEX Z_Trigger_UNIQUE_identifier ON ZTRIGGER (ZIDENTIFIER COLLATE BINARY ASC);

CREATE INDEX ZTRIGGEREVENT_ZTRIGGER_INDEX ON ZTRIGGEREVENT (ZTRIGGER);

CREATE UNIQUE INDEX Z_TriggerEvent_UNIQUE_identifier ON ZTRIGGEREVENT (ZIDENTIFIER COLLATE BINARY ASC);

CREATE INDEX ZTRUSTEDDOMAIN_ZSHORTCUT_INDEX ON ZTRUSTEDDOMAIN (ZSHORTCUT);

CREATE INDEX Z_VCVoiceShortcutSuggestionListManagedObject_byAppBundleID ON ZVCVOICESHORTCUTSUGGESTIONLISTMANAGEDOBJECT (ZASSOCIATEDAPPBUNDLEIDENTIFIER COLLATE BINARY ASC);

CREATE UNIQUE INDEX Z_VCVoiceShortcutSuggestionListManagedObject_UNIQUE_associatedAppBundleIdentifier ON ZVCVOICESHORTCUTSUGGESTIONLISTMANAGEDOBJECT (ZASSOCIATEDAPPBUNDLEIDENTIFIER COLLATE BINARY ASC);

CREATE INDEX ZVCVOICESHORTCUTSYNCSTATEMANAGEDOBJECT_ZVOICESHORTCUT_INDEX ON ZVCVOICESHORTCUTSYNCSTATEMANAGEDOBJECT (ZVOICESHORTCUT);

CREATE TRIGGER Z_DA_ZSHORTCUTRUNEVENT_Shortcut_runEventsCount_PARAMETER_INSERT AFTER INSERT ON ZSHORTCUTRUNEVENT FOR EACH ROW WHEN (NEW.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZRUNEVENTSCOUNT = IFNULL(ZRUNEVENTSCOUNT, 0) + 1 WHERE Z_PK = NEW.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'runEventsCount', ZRUNEVENTSCOUNT) FROM ZSHORTCUT WHERE Z_PK = NEW.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZSHORTCUTRUNEVENT_Shortcut_runEventsCount_PARAMETER_UPDATE_INCREMENT AFTER UPDATE OF ZSHORTCUT ON ZSHORTCUTRUNEVENT FOR EACH ROW WHEN (NEW.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZRUNEVENTSCOUNT = ZRUNEVENTSCOUNT + 1 WHERE Z_PK = NEW.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'runEventsCount', ZRUNEVENTSCOUNT) FROM ZSHORTCUT WHERE Z_PK = NEW.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZSHORTCUTRUNEVENT_Shortcut_runEventsCount_PARAMETER_UPDATE_DECREMENT AFTER UPDATE OF ZSHORTCUT ON ZSHORTCUTRUNEVENT FOR EACH ROW WHEN (OLD.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZRUNEVENTSCOUNT = ZRUNEVENTSCOUNT - 1 WHERE Z_PK = OLD.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'runEventsCount', ZRUNEVENTSCOUNT) FROM ZSHORTCUT WHERE Z_PK = OLD.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZSHORTCUTRUNEVENT_Shortcut_runEventsCount_PARAMETER_DELETE AFTER DELETE ON ZSHORTCUTRUNEVENT FOR EACH ROW WHEN (OLD.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZRUNEVENTSCOUNT = ZRUNEVENTSCOUNT - 1 WHERE Z_PK = OLD.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'runEventsCount', ZRUNEVENTSCOUNT) FROM ZSHORTCUT WHERE Z_PK = OLD.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZSHORTCUT_Shortcut_runEventsCount_SOURCE_INSERT AFTER INSERT ON ZSHORTCUT FOR EACH ROW BEGIN UPDATE ZSHORTCUT SET ZRUNEVENTSCOUNT = (SELECT IFNULL(COUNT(ZSHORTCUT), 0) FROM ZSHORTCUTRUNEVENT WHERE ZSHORTCUT = NEW.Z_PK) WHERE Z_PK = NEW.Z_PK; SELECT NSCoreDataDATriggerInsertUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'runEventsCount', ZRUNEVENTSCOUNT) FROM ZSHORTCUT WHERE Z_PK = NEW.Z_PK; END;

CREATE TRIGGER Z_DA_ZTRIGGER_Shortcut_triggerCount_PARAMETER_INSERT AFTER INSERT ON ZTRIGGER FOR EACH ROW WHEN (NEW.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZTRIGGERCOUNT = IFNULL(ZTRIGGERCOUNT, 0) + 1 WHERE Z_PK = NEW.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'triggerCount', ZTRIGGERCOUNT) FROM ZSHORTCUT WHERE Z_PK = NEW.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZTRIGGER_Shortcut_triggerCount_PARAMETER_UPDATE_INCREMENT AFTER UPDATE OF ZSHORTCUT ON ZTRIGGER FOR EACH ROW WHEN (NEW.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZTRIGGERCOUNT = ZTRIGGERCOUNT + 1 WHERE Z_PK = NEW.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'triggerCount', ZTRIGGERCOUNT) FROM ZSHORTCUT WHERE Z_PK = NEW.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZTRIGGER_Shortcut_triggerCount_PARAMETER_UPDATE_DECREMENT AFTER UPDATE OF ZSHORTCUT ON ZTRIGGER FOR EACH ROW WHEN (OLD.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZTRIGGERCOUNT = ZTRIGGERCOUNT - 1 WHERE Z_PK = OLD.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'triggerCount', ZTRIGGERCOUNT) FROM ZSHORTCUT WHERE Z_PK = OLD.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZTRIGGER_Shortcut_triggerCount_PARAMETER_DELETE AFTER DELETE ON ZTRIGGER FOR EACH ROW WHEN (OLD.ZSHORTCUT NOT NULL) BEGIN UPDATE ZSHORTCUT SET ZTRIGGERCOUNT = ZTRIGGERCOUNT - 1 WHERE Z_PK = OLD.ZSHORTCUT; SELECT NSCoreDataDATriggerUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'triggerCount', ZTRIGGERCOUNT) FROM ZSHORTCUT WHERE Z_PK = OLD.ZSHORTCUT; END;

CREATE TRIGGER Z_DA_ZSHORTCUT_Shortcut_triggerCount_SOURCE_INSERT AFTER INSERT ON ZSHORTCUT FOR EACH ROW BEGIN UPDATE ZSHORTCUT SET ZTRIGGERCOUNT = (SELECT IFNULL(COUNT(ZSHORTCUT), 0) FROM ZTRIGGER WHERE ZSHORTCUT = NEW.Z_PK) WHERE Z_PK = NEW.Z_PK; SELECT NSCoreDataDATriggerInsertUpdatedAffectedObjectValue('ZSHORTCUT', Z_ENT, Z_PK, 'triggerCount', ZTRIGGERCOUNT) FROM ZSHORTCUT WHERE Z_PK = NEW.Z_PK; END;

CREATE TABLE Z_PRIMARYKEY (Z_ENT INTEGER PRIMARY KEY, Z_NAME VARCHAR, Z_SUPER INTEGER, Z_MAX INTEGER);

CREATE TABLE Z_METADATA (Z_VERSION INTEGER PRIMARY KEY, Z_UUID VARCHAR(255), Z_PLIST BLOB);

CREATE TABLE Z_MODELCACHE (Z_CONTENT BLOB)